### ISSUE TITLE
Shift the docs to readthedocs

### ISSUE THREAD

**Issue by DaffyTheDuck** [andrefpoliveira/Pansy#11]
It would be great if we shift the README.md to readthedocs, it will be really nice for new contributors as they can make the offline copy for themselves 

labels can be added like:-  Hacktoberfest

P.S.- I'm working on this :smile:

**Comment by DaffyTheDuck** [comment]
is the favicon available? since #2 is closed, i'll add it to the docs then :smile:

**Comment by andrefpoliveira** [comment]
@DaffyTheDuck yes! It's [here](https://github.com/andrefpoliveira/Pansy/blob/master/images/Pansy.png)! 😄

**Comment by DaffyTheDuck** [comment]
Thanks I'm adding it

**Comment by DaffyTheDuck** [comment]
![Docs](https://user-images.githubusercontent.com/34976093/94363160-f8fc7880-00dd-11eb-89df-67cc036c3f08.png)
I've updated the image in favicon and logo, but in my view logo is looking quite small, any suggestion for size of logo?
