### ISSUE TITLE
Add new Built-in Functions

### ISSUE THREAD

**Issue by andrefpoliveira** [andrefpoliveira/Pansy#13]
Hey! Currently Pansy doesn't have a lot of built-in functions. That's were you come in!  
  
If you want to work on any of these please say so, like this no one is working on each other functions.  
  
# How to add new functions
To insert a new function you need to go to ```lib/interpreter.py```. You can search for ```def execute_print``` and you will find below all the built-in functions created so far. You can use those as examples!

Then you search for ```BuiltInFunction.print``` and you will get 2 results! Follow those examples to add your function.
  
# List
Below is a list of the current built-in functions, some ideas and who is working on them:
- [x] ```print```
- [x] ```input```
- [x] ```is_number```
- [x] ```is_string```
- [x] ```is_list```
- [x] ```is_function```
- [x] ```append```
- [x] ```pop```
- [x] ```set```
- [x] ```extend```
- [x] ```get```
- [x] ```run```
- [x] ```len```
- [x] ```to_str```
- [x] ```to_int```
- [x] ```to_float```
- [x] ```imports```
- [x] ```abs```
- [x] ```has_key```
- [x] ```min``` (between 2 numbers) @DaffyTheDuck
- [x] ```max``` (between 2 numbers) @DaffyTheDuck
- [x] ```slice```
- [x] ```split```
- [x] ```oct``` @DaffyTheDuck 
- [x] ```fact``` @Zaidtech

If you have any other idea feel free to share it down in the comments so it can be added to the list.

**Comment by andrefpoliveira** [comment]
@DaffyTheDuck not currently planned because I need to make a structure like the "For each" for that to work

**Comment by sanatdeshpande1** [comment]
Is there a type() function to return the type of variable? Or string operation functions like slice(), split()?

**Comment by andrefpoliveira** [comment]
Currently no 😄 You can try to make if you want

**Comment by sanatdeshpande1** [comment]
Alright. I'll go through the files and see if I can implement it

**Comment by andrefpoliveira** [comment]
Sure! @sanatdeshpande1 then tell me in each ones you want to work on

**Comment by Zaidtech** [comment]
Hey what about time() function or current time related module

**Comment by andrefpoliveira** [comment]
@Zaidtech I was thinking about making a date import file, like Math in Python, but I need to setup somethings first

**Comment by Zaidtech** [comment]
Ok! then, any other function i can implement :sweat_smile:

**Comment by DaffyTheDuck** [comment]
any thought about pow() and oct()?

**Comment by andrefpoliveira** [comment]
@DaffyTheDuck pow() is already implemented as the char '^'
`3^2
@ 9`

But you can always implement oct() if you want

**Comment by Zaidtech** [comment]
@DaffyTheDuck  what about a fact() function !

**Comment by andrefpoliveira** [comment]
@Zaidtech for factorial?

**Comment by DaffyTheDuck** [comment]
Can you assign me on oct?

**Comment by Zaidtech** [comment]
@andrefpoliveira Sure !

**Comment by andrefpoliveira** [comment]
@DaffyTheDuck @Zaidtech done

**Comment by DaffyTheDuck** [comment]
I already made PR for that :smile: @andrefpoliveira

**Comment by Zaidtech** [comment]
Can anyone plz, guide me in adding a new method I am unable to understand

**Comment by Zaidtech** [comment]
`	def execute_fact(self, exec_ctx):
		number = exec_ctx.symbol_table.get(number)
		if not isinstance(number, Number):
			return RTResult().failure(errors.RTError(
				self.pos_start, self.pos_end,
				f"Argument must be a number",
				exec_ctx
			))
			fact = 1;
			for _ in range(1,number+1):
				fact = number*fact
				number = number -1

			number = fact	

		return RTResult().success(Number(number.value))
		
		execute_max.arg_names = [number]`

**Comment by Zaidtech** [comment]
`	def execute_fact(self, exec_ctx):
		number = exec_ctx.symbol_table.get(number)
		if not isinstance(number, Number):
			return RTResult().failure(errors.RTError(
				self.pos_start, self.pos_end,
				f"Argument must be a number",
				exec_ctx
			))
			fact = 1;
			for _ in range(1,number+1):
				fact = number*fact
				number = number -1

			number = fact	

		return RTResult().success(Number(number.value))
		
		execute_max.arg_names = [number]`

**Comment by Zaidtech** [comment]
` 
	def execute_fact(self, exec_ctx):
		number = exec_ctx.symbol_table.get(number)
		if not isinstance(number, Number):
			return RTResult().failure(errors.RTError(
				self.pos_start, self.pos_end,
				f"Argument must be a number",
				exec_ctx
			))
			fact = 1;
			for _ in range(1,number+1):
				fact = number*fact
				number = number -1

			number = fact	

		return RTResult().success(Number(number.value))
		
		execute_max.arg_names = [number]
`
I tried this is it okay!!

**Comment by Zaidtech** [comment]
def execute_fact(self, exec_ctx):
		number = exec_ctx.symbol_table.get(number)
		if not isinstance(number, Number):
			return RTResult().failure(errors.RTError(
				self.pos_start, self.pos_end,
				f"Argument must be a number",
				exec_ctx
			))
			fact = 1;
			for _ in range(1,number+1):
				fact = number*fact
				number = number -1

			number = fact	

		return RTResult().success(Number(number.value))
		
		execute_max.arg_names = [number]



I tried this , is it okay?

**Comment by andrefpoliveira** [comment]
@Zaidtech can you join the discord server? It is easier to talk about that

**Comment by Zaidtech** [comment]
@andrefpoliveira I made a pr, kindly review the same.

**Comment by sanatdeshpande1** [comment]
Hi, I have completed the implementation of split_char() that splits a string by a given input character and creates a list out of it. Shall I create a PR for it?

**Comment by andrefpoliveira** [comment]
@sanatdeshpande1 yes please 😄

**Comment by sanatdeshpande1** [comment]
@andrefpoliveira Done! Please check.

**Comment by sanatdeshpande1** [comment]
Hi @andrefpoliveira  I just completed implementing slice() for slicing a string at a given start and end index. Shall I create a PR?

**Comment by andrefpoliveira** [comment]
@sanatdeshpande1 Giving an int for the beginning and an int for the end?

**Comment by sanatdeshpande1** [comment]
Yes

**Comment by andrefpoliveira** [comment]
@sanatdeshpande1 go ahead!

**Comment by sanatdeshpande1** [comment]
@andrefpoliveira I have created a PR for slice()

**Comment by himanshuvarandani** [comment]
Hello @andrefpoliveira, is there any requirement of function to check the number is prime or not?

**Comment by andrefpoliveira** [comment]
@himanshuvarandani currently there is no function to do check that. You can implement if you want

**Comment by himanshuvarandani** [comment]
Okay, I will send a pr today.
