### ISSUE TITLE
Logo Needed

### ISSUE THREAD

**Issue by andrefpoliveira** [andrefpoliveira/Pansy#2]
Hey :smile:!

[Pansy](https://www.google.com/search?q=pansy&tbm=isch&ved=2ahUKEwjOzZOzjLfrAhVFYxoKHfHFA7UQ2-cCegQIABAA&oq=pansy&gs_lcp=CgNpbWcQAzIECCMQJzIECCMQJzIECAAQQzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAA6BAgAEB5Qmp45WM2rOWD7rTloAHAAeACAAeEBiAHPCZIBBTAuNi4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=fWdFX46bJ8XGafGLj6gL&bih=657&biw=1366) is such a beautiful flower :wink: and in my country it is known as **Amor Perfeito** ( _Perfect Love_ in english )

Well basically, I would like to get a logo for my programming language!

Surprise me :smiley:!!

**Comment by Shreenabh664** [comment]
Is this still open? Can I do a PR for this? (I can make some fairly good logos ig)

**Comment by Shreenabh664** [comment]
PR: https://github.com/andrefpoliveira/Pansy/pull/14
