### ISSUE TITLE
[BUG] Not able to use if conditions!

### ISSUE THREAD

**Issue by adithraghavs** [andrefpoliveira/Pansy#38]
**Description**
Not able to use if conditions: gives an error 
```
Traceback (most recent call last):
  File <stdin>, line 1, in <program>
  File <stdin>, line 1, in run
Runtime Error: Failed to finish executing script "bug.pansy"
Traceback (most recent call last):
  File bug.pansy, line 2, in <program>
Runtime Error: Illegal operation


if food == "pizza":
   ^^^^^^^^^^^^^^^^
  print("Yammi!")
^^^^^^^^^^^^^^^^^
end
^^^

run("bug.pansy")
```
I am on Windows

**To Reproduce The Error**
1. Start Pansy with the command `python shell.pansy`
2. Execute the code `run("bug.pansy")` in the shell (I have created a file called bug.pansy for this issue)
##### Bug.pansy:
var food = "pizza"
if food == "pizza":
  print("Yammi!")
end
This was an example in the documentation.

*Note:*
If you write 
```
var n = 10
if n == 10:
  print("n = 10")
end
```
This works. It is a problem with checking strings.

**Expected behavior**
Expected to print Yammi! Instead printed illegal operation error

**Screenshots**
![image](https://user-images.githubusercontent.com/65845669/110737883-4f0c4500-8254-11eb-8e50-a04bcb7de977.png)

![image](https://user-images.githubusercontent.com/65845669/110737938-68ad8c80-8254-11eb-813b-f081084b29dc.png)

![image](https://user-images.githubusercontent.com/65845669/110738032-9266b380-8254-11eb-99d5-c15cc85b8266.png)

![image](https://user-images.githubusercontent.com/65845669/110738057-9d214880-8254-11eb-8569-b8e526ab74a0.png)

I am on Windows x64 Intel.

**Comment by andrefpoliveira** [comment]
Thanks for the help!!

**Comment by adithraghavs** [comment]
Thanks, bro!
